# Generated by Django 5.2.1 on 2026-05-13 13:08

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AcademicYear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=32, unique=True)),
                ("starts_on", models.DateField()),
                ("ends_on", models.DateField()),
                ("is_active", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=16, unique=True)),
                ("name", models.CharField(max_length=180)),
                ("college_name", models.CharField(blank=True, max_length=220)),
                ("university_name", models.CharField(blank=True, max_length=220)),
                ("logo", models.ImageField(blank=True, upload_to="department-logos/")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=32)),
                ("title", models.CharField(max_length=220)),
                (
                    "course_type",
                    models.CharField(
                        choices=[
                            ("THEORY", "Theory"),
                            ("LAB", "Laboratory"),
                            ("PROJECT", "Project"),
                            ("ELECTIVE", "Elective"),
                            ("INTERDISCIPLINARY", "Interdisciplinary"),
                        ],
                        default="THEORY",
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted"),
                            ("UNDER_REVIEW", "Under review"),
                            ("CHANGES_REQUESTED", "Changes requested"),
                            ("APPROVED", "Approved"),
                            ("PUBLISHED", "Published"),
                            ("LOCKED", "Locked"),
                        ],
                        default="DRAFT",
                        max_length=32,
                    ),
                ),
                ("lecture_hours", models.PositiveSmallIntegerField(default=0)),
                ("tutorial_hours", models.PositiveSmallIntegerField(default=0)),
                ("practical_hours", models.PositiveSmallIntegerField(default=0)),
                (
                    "credits",
                    models.DecimalField(decimal_places=1, default=0, max_digits=4),
                ),
                ("internal_marks", models.PositiveSmallIntegerField(default=0)),
                ("external_marks", models.PositiveSmallIntegerField(default=0)),
                (
                    "duration_hours",
                    models.DecimalField(decimal_places=1, default=3, max_digits=3),
                ),
                ("pre_requisites", models.TextField(blank=True)),
                ("objectives", models.TextField(blank=True)),
                ("syllabus_intro", models.TextField(blank=True)),
                ("online_resources", models.JSONField(blank=True, default=list)),
                ("section_order", models.JSONField(blank=True, default=list)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_courses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "faculty",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_courses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["semester__number", "code"],
            },
        ),
        migrations.CreateModel(
            name="AssessmentScheme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("component", models.CharField(max_length=120)),
                ("marks", models.PositiveSmallIntegerField()),
                ("description", models.TextField(blank=True)),
                ("order", models.PositiveSmallIntegerField(default=1)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessments",
                        to="curriculum.course",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Module",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("number", models.PositiveSmallIntegerField()),
                ("title", models.CharField(max_length=220)),
                ("contact_hours", models.PositiveSmallIntegerField(default=0)),
                ("content", models.TextField()),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modules",
                        to="curriculum.course",
                    ),
                ),
            ],
            options={
                "ordering": ["number"],
                "unique_together": {("course", "number")},
            },
        ),
        migrations.CreateModel(
            name="ReferenceBook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=260)),
                ("authors", models.CharField(blank=True, max_length=260)),
                ("publisher", models.CharField(blank=True, max_length=180)),
                ("edition", models.CharField(blank=True, max_length=80)),
                ("year", models.CharField(blank=True, max_length=16)),
                ("is_textbook", models.BooleanField(default=False)),
                ("order", models.PositiveSmallIntegerField(default=1)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reference_books",
                        to="curriculum.course",
                    ),
                ),
            ],
            options={
                "ordering": ["is_textbook", "order"],
            },
        ),
        migrations.CreateModel(
            name="Semester",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "number",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("ordinance", models.CharField(blank=True, max_length=80)),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="semesters",
                        to="curriculum.academicyear",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="semesters",
                        to="curriculum.department",
                    ),
                ),
            ],
            options={
                "ordering": ["academic_year__starts_on", "department__code", "number"],
                "unique_together": {("department", "academic_year", "number")},
            },
        ),
        migrations.AddField(
            model_name="course",
            name="semester",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courses",
                to="curriculum.semester",
            ),
        ),
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=220)),
                ("description", models.TextField(blank=True)),
                ("order", models.PositiveSmallIntegerField(default=1)),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topics",
                        to="curriculum.module",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="CourseOutcome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=16)),
                ("description", models.TextField()),
                ("bloom_level", models.CharField(blank=True, max_length=80)),
                ("order", models.PositiveSmallIntegerField(default=1)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outcomes",
                        to="curriculum.course",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "code"],
                "unique_together": {("course", "code")},
            },
        ),
        migrations.CreateModel(
            name="CourseVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version_number", models.PositiveIntegerField()),
                ("snapshot", models.JSONField()),
                ("change_summary", models.CharField(blank=True, max_length=260)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="curriculum.course",
                    ),
                ),
                (
                    "edited_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="course_versions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "previous_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="curriculum.courseversion",
                    ),
                ),
            ],
            options={
                "ordering": ["-version_number"],
                "unique_together": {("course", "version_number")},
            },
        ),
        migrations.CreateModel(
            name="Experiment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("number", models.PositiveSmallIntegerField()),
                ("title", models.CharField(max_length=220)),
                ("description", models.TextField(blank=True)),
                ("hours", models.PositiveSmallIntegerField(default=2)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="experiments",
                        to="curriculum.course",
                    ),
                ),
            ],
            options={
                "ordering": ["number"],
                "unique_together": {("course", "number")},
            },
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(fields=["status"], name="curriculum__status_230a2d_idx"),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(
                fields=["course_type"], name="curriculum__course__2bcfe7_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="course",
            unique_together={("semester", "code")},
        ),
    ]
