# Generated by Django 5.2.1 on 2026-05-13 14:25

import apps.curriculum.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curriculum", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="objectives",
            field=models.TextField(
                blank=True, validators=[django.core.validators.MaxLengthValidator(300)]
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="pre_requisites",
            field=models.TextField(
                blank=True, validators=[django.core.validators.MaxLengthValidator(300)]
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="syllabus_intro",
            field=models.TextField(
                blank=True, validators=[django.core.validators.MaxLengthValidator(800)]
            ),
        ),
        migrations.AlterField(
            model_name="module",
            name="content",
            field=models.TextField(
                validators=[django.core.validators.MaxLengthValidator(500)]
            ),
        ),
        migrations.AlterField(
            model_name="topic",
            name="description",
            field=models.TextField(
                blank=True, validators=[django.core.validators.MaxLengthValidator(500)]
            ),
        ),
        migrations.CreateModel(
            name="CourseInvitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("email", models.EmailField(max_length=254)),
                (
                    "token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        default=apps.curriculum.models.default_invitation_expiry
                    ),
                ),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "accepted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="accepted_course_invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitations",
                        to="curriculum.course",
                    ),
                ),
                (
                    "invited_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_course_invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["email"], name="curriculum__email_4104b4_idx"),
                    models.Index(fields=["token"], name="curriculum__token_1c4038_idx"),
                ],
            },
        ),
    ]
