# Generated by Django 5.2.1 on 2026-05-25 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "curriculum",
            "0002_alter_course_objectives_alter_course_pre_requisites_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="lecture_credits",
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name="course",
            name="practical_credits",
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name="course",
            name="tutorial_credits",
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name="course",
            name="course_type",
            field=models.CharField(
                choices=[
                    ("THEORY", "Theory"),
                    ("LAB", "Laboratory"),
                    ("THEORY_LAB", "Theory and Practical"),
                    ("PROJECT", "Project"),
                    ("ELECTIVE", "Elective"),
                    ("INTERDISCIPLINARY", "Interdisciplinary"),
                ],
                default="THEORY",
                max_length=32,
            ),
        ),
    ]
