# Generated by Django 5.2.1 on 2026-05-13 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("curriculum", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CurriculumTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=140)),
                (
                    "html_template",
                    models.TextField(
                        help_text="Django template source for official PDF sections."
                    ),
                ),
                (
                    "css",
                    models.TextField(
                        help_text="Paged media CSS matching the official university template."
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "template_pdf",
                    models.FileField(blank=True, upload_to="official-templates/"),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="templates",
                        to="curriculum.department",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PublishedCurriculum",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("pdf", models.FileField(upload_to="published-curricula/")),
                ("docx", models.FileField(blank=True, upload_to="published-docx/")),
                ("version_label", models.CharField(max_length=80)),
                ("is_public", models.BooleanField(default=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="published_curricula",
                        to="curriculum.academicyear",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="published_curricula",
                        to="curriculum.department",
                    ),
                ),
                (
                    "published_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="published_curricula",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="published_curricula",
                        to="publishing.curriculumtemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("department", "academic_year", "version_label")},
            },
        ),
    ]
