# Generated by Django 5.2.1 on 2026-05-15 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("publishing", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="curriculumtemplate",
            options={"ordering": ["-updated_at"]},
        ),
        migrations.AddField(
            model_name="curriculumtemplate",
            name="is_locked",
            field=models.BooleanField(
                default=False,
                help_text="Locked after publish — prevents edits that would invalidate historical PDFs.",
            ),
        ),
        migrations.AddField(
            model_name="curriculumtemplate",
            name="version",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Incremented on each edit. Published curricula store the version they used.",
            ),
        ),
        migrations.AddField(
            model_name="publishedcurriculum",
            name="render_metrics",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Page count, course count, overflow warnings recorded at render time.",
            ),
        ),
        migrations.AddField(
            model_name="publishedcurriculum",
            name="template_snapshot",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Frozen copy of the template CSS and HTML at the time of publish — immutable audit record.",
            ),
        ),
    ]
